version: '3.9'

services:

  api:
      # It will look for a dockerfile in the project root and build it
      build: .
      # Exposes the port 5000 from a container and binds it to a random port
      ports:
          - "5000"
      restart: on-failure
      environment:
          PORT: 5000
          DATABASE_URI: "mongodb+srv://admin:admin33@cluster0.iqkyn.mongodb.net/mux-mongodb?retryWrites=true&w=majority"
          DATABASE_NAME: "mux-mongodb"

      # Connects the API to a common api.network bridge
      networks: 
          - "api.network"

      # Starts up 5 replicas of the same image
      deploy:
          replicas: 5
      # volumes:
          # - .:/app
  
  # nginx container
  nginx:
      # specifies the latest nginx image
      image: nginx:latest
      # Connects the conf file of the container to the conf file in our folder
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # It will start up the nginx only when all api containers have started
      depends_on: 
          - api
      # Connects the port 80 of the nginx container to localhost:80 or localhost
      ports: 
          - "80:80"
      networks: 
          - "api.network"
  
# declares network used to connect all the apps
networks: 
    api.network: